site_name: My Docs
site_url: https://seasawher.github.io/mkdocs-demo/
nav:
  - Home: index.md
  - Reference:
    - Hoge: Reference/hoge.md
  - About:
    - About: about.md
theme:
  name: material
  language: ja
  features:
    # これによりサイト上部にナビゲーションタブが表示されるようになる
    - navigation.tabs
  palette:
    # ダーク/ライトモードの切り替え
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences