site_name: My Docs
site_url: https://seasawher.github.io/mkdocs-demo/
nav:
  - Home: index.md
  - Reference:
    - Hoge: Reference/hoge.md
  - About:
    - About: about.md
theme:
  name: material
  features:
    # これによりサイト上部にナビゲーションタブが表示されるようになる
    - navigation.tabs